name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify Node.js version (update as needed)

    - name: Clean node_modules
      run: rm -rf node_modules # Remove existing node_modules

    - name: Install dependencies
      run: npm ci  # Use npm ci to install dependencies cleanly

    - name: Install Vite globally
      run: npm install -g vite

    - name: Build project
      run: npm run build  # Runs the Vite build command

    - name: Deploy to GitHub Pages
      run: npx gh-pages -d dist  # Deploy to GitHub Pages
