name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify your Node.js version (you can adjust it to the version you're using)

    - name: Install dependencies
      run: npm install  # Installs the project dependencies

    - name: Grant execute permission to Vite
      run: chmod +x node_modules/.bin/vite  # Ensure Vite has execution permissions

    - name: Build project
      run: npm run build  # Runs the Vite build command

    - name: Deploy to GitHub Pages
      run: npx gh-pages -d dist  # Deploy to GitHub Pages
